# Generated by Django 4.0.3 on 2022-03-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_date_created_product_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
